version: '3.4'
services:
  erp-produto:
    image: dehemart/erp-produto:latest
    container_name: erp-produto
    ports:
      - 8810:8810
    environment:
      PORT: 8810
      SPRING_PROFILES_ACTIVE: local
      SPRING_CLOUD_CONFIG_URI: http://172.17.0.1:8888
